### ISSUE TITLE
Default program's clock out can cause multiple triggers for each note at slower clocks

### ISSUE THREAD

**Issue by theacodes** [theacodes/Winterbloom-Sol-software#7]
Since `state.clock` can remain the same value between subsequent calls to `loop`, if the clock is slow enough loop will actually retrigger the output multiple times for a single clock.

A possible fix is to make it possible to "latch" `Trigger`/`Retrigger` objects - preventing them from triggering again until `unlatched`.

Another possible fix is to make `helpers.should_trigger_clock` memoize the last `state.clock` value that it returned `True` for and return `False` if it sees it again.

**Comment by jmcneil86043** [comment]
I’d like to vote for this issue to be fixed. I was going to write up the bug myself but just found this. The double trigger makes the clock unusable for things like a tap input for a delay. Otherwise I love Sol. It is a perfect companion for my Deluge.

**Comment by theacodes** [comment]
Hey folks, would one of you be willing to try out this code and see if it fixes the issue for you?

You'll need to:

1. Unzip the files
2. Copy them to your `CIRCUITPY` drive, replacing any existing files
3. Power cycle your device

[sol-2021.3.28.zip](https://github.com/wntrblm/Sol/files/6393368/sol-2021.3.28.zip)

**Comment by joehillaintdead** [comment]
> Hey folks, would one of you be willing to try out this code and see if it fixes the issue for you?
> 
> You'll need to:
> 
>     1. Unzip the files
> 
>     2. Copy them to your `CIRCUITPY` drive, replacing any existing files
> 
>     3. Power cycle your device
> 
> 
> [sol-2021.3.28.zip](https://github.com/wntrblm/Sol/files/6393368/sol-2021.3.28.zip)

I've loaded this and sent MIDI. Sol sends one clock pulse on gate 3 and then goes into blinky mode: 
7 yellow, 4 magenta

from the serial console:

```
code.py output:
Traceback (most recent call last):
  File "code.py", line 84, in <module>
  File "/lib/winterbloom_sol/__init__.py", line 41, in run
  File "/lib/winterbloom_sol/sol.py", line 370, in run
  File "/lib/winterbloom_sol/sol.py", line 368, in run
  File "code.py", line 75, in loop
  File "/lib/winterbloom_sol/helpers.py", line 69, in should_trigger_clock
AttributeError: 'NoneType' object has no attribute 'type'

Code done running.
```

**Comment by theacodes** [comment]
Ah, I see what went wrong. Can you give this one a try when you get a chance?

[sol-2021.4.29.zip](https://github.com/wntrblm/Sol/files/6399072/sol-2021.4.29.zip)

**Comment by jmcneil86043** [comment]
This works for me!! Nice clean pulses. I tried it at 16th and 1/4 notes at a wide range of BPM
Thank you for the quick fix!

**Comment by theacodes** [comment]
Thanks for testing! This has now been released: https://github.com/wntrblm/Sol/releases/tag/2021.4.30
